Update chart-sync

diff --git a/script/ci/chart-sync b/script/ci/chart-sync
--- a/script/ci/chart-sync
+++ b/script/ci/chart-sync
@@ -33,39 +33,42 @@ main() {
   declare -r basedir="${1}"
   declare -r passwordkey="${2}"
   
-  setup_helm_client
   
-  # Basic validations before taking any actions
-  if ! validate_arguments "${@}"; then
-    usage
-    exit 1
-  fi
-  validate_basedir "${basedir}"
-  exit_if_there_is_no_change "${basedir}"
-  if is_branch_behind_master; then
-    echo "[DEBUG] Stopped because local branch is older than remote one" >&2
-    return 0
-  fi
+  echo $passwordkey
   
-  show_changed_dirs "${basedir}"
-  # Temporary sync directory from which all the changed charts will be pushed to remote helm repo
-  mkdir -p "${basedir}-sync"
-  echo "[INFO] Packaging the modified helm charts and putting in ${basedir}-sync"
-  for dir in $(changed_chart_dirs "${basedir}"); do
-    if [ -d "${dir}" ]; then
-      if helm dependency build "${dir}"; then
-        helm package --destination "${basedir}-sync" "${dir}"
-      else
-        echo "[ERROR] Problem building dependencies. Skipping packaging of '${dir}'"
-        exit 1
-      fi
-    fi
-  done
+#   setup_helm_client
   
-  echo "[INFO] Syncing the modified helm charts"
-  for file in "${basedir}-sync"/*; do
-    echo "curl --data-binary @${file} https://mercari:$(eval echo \$${passwordkey})@chartmuseum.dev.citadelapps.com/api/charts"
-  done
+#   # Basic validations before taking any actions
+#   if ! validate_arguments "${@}"; then
+#     usage
+#     exit 1
+#   fi
+#   validate_basedir "${basedir}"
+#   exit_if_there_is_no_change "${basedir}"
+#   if is_branch_behind_master; then
+#     echo "[DEBUG] Stopped because local branch is older than remote one" >&2
+#     return 0
+#   fi
+  
+#   show_changed_dirs "${basedir}"
+#   # Temporary sync directory from which all the changed charts will be pushed to remote helm repo
+#   mkdir -p "${basedir}-sync"
+#   echo "[INFO] Packaging the modified helm charts and putting in ${basedir}-sync"
+#   for dir in $(changed_chart_dirs "${basedir}"); do
+#     if [ -d "${dir}" ]; then
+#       if helm dependency build "${dir}"; then
+#         helm package --destination "${basedir}-sync" "${dir}"
+#       else
+#         echo "[ERROR] Problem building dependencies. Skipping packaging of '${dir}'"
+#         exit 1
+#       fi
+#     fi
+#   done
+  
+#   echo "[INFO] Syncing the modified helm charts"
+#   for file in "${basedir}-sync"/*; do
+#     echo "curl --data-binary @${file} https://mercari:$(eval echo \$${passwordkey})@chartmuseum.dev.citadelapps.com/api/charts"
+#   done
   
 }
 
